// jsonOptions.js
const jsonOptions = {
  Accelerometer: {
    module_name: "M3",
    module_description: "Accelerometer",
    "Module Type": "self",
    Number_of_Pins: "5",
    pins: [
      {
        Pno: "1",
        name: "VDD",
        type: "GP",
        interface: "powerOUT",
        each_mandatory: true,
        con_port: "VOUT",
      },
      {
        Pno: "2",
        name: "VOUT",
        type: "GP",
        interface: "powerGND",
        each_mandatory: false,
        con_port: "GND",
      },
      {
        Pno: "3",
        name: "SDA",
        type: "GP",
        interface: "powerIN",
        each_mandatory: false,
        con_port: "SDA",
      },
      {
        Pno: "4",
        name: "SCL",
        type: "GP",
        interface: "powerIN",
        each_mandatory: false,
        con_port: "SCL",
      },
      {
        Pno: "5",
        name: "INT",
        type: "GP",
        interface: "powerIN",
        each_mandatory: false,
        con_port: "INT",
      },
    ],
  },
  TPS62240: {
    module_name: "M1",
    module_description: "TPS62240",
    "Module Type": "self",
    Number_of_Pins: "4",
    pins: [
      {
        Pno: "1",
        name: "VIN",
        type: "GP",
        interface: "powerIN",
        con_port: "VOUT",
        each_mandatory: true,
      },
      {
        Pno: "2",
        name: "SW",
        type: "GP",
        interface: "powerGND",
        con_port: "SW",
        each_mandatory: false,
      },
      {
        Pno: "3",
        name: "VIN2",
        type: "GP",
        interface: "powerGND",
        con_port: "FB",
        each_mandatory: true,
      },
      {
        Pno: "4",
        name: "VOUT",
        type: "GP",
        interface: "powerOUT",
        con_port: "GND",
        each_mandatory: true,
      },
    ],
  },
  Microcontroller: {
    module_name: "M4",
    module_description: "Microcontroller",
    "Module Type": "self",
    Number_of_Pins: "8",
    pins: [
      {
        Pno: "1",
        name: "VIN",
        type: "GP",
        interface: "powerIN",
        each_mandatory: true,
        con_port: "VOUT",
      },
      {
        Pno: "2",
        name: "SCL1",
        type: "GP",
        interface: "powerIN",
        each_mandatory: false,
        con_port: "SCL1",
      },
      {
        Pno: "3",
        name: "SDA1",
        type: "GP",
        interface: "powerIN",
        each_mandatory: false,
        con_port: "SDA1",
      },
      {
        Pno: "4",
        name: "INT1",
        type: "GP",
        interface: "powerIN",
        each_mandatory: false,
        con_port: "INT1",
      },
      {
        Pno: "5",
        name: "GND",
        type: "GP",
        interface: "powerGND",
        each_mandatory: false,
        con_port: "GND",
      },
      {
        Pno: "6",
        name: "SCL2",
        type: "GP",
        interface: "powerOUT",
        each_mandatory: false,
        con_port: "SCL2",
      },
      {
        Pno: "7",
        name: "INT2",
        type: "GP",
        interface: "powerIN",
        each_mandatory: false,
        con_port: "INT2",
      },
      {
        Pno: "8",
        name: "SDA2",
        type: "GP",
        interface: "powerIN",
        each_mandatory: false,
        con_port: "SDA2",
      },
    ],
  },
  MAX30102: {
    module_name: "M2",
    module_description: "MAX30102",
    "Module Type": "self",
    Number_of_Pins: "7",
    pins: [
      {
        Pno: "1",
        name: "VDD",
        type: "GP",
        interface: "powerIN",
        each_mandatory: true,
        con_port: "VOUT",
      },
      {
        Pno: "2",
        name: "VLED+",
        type: "GP",
        interface: "powerGND",
        each_mandatory: false,
        con_port: "VLED+",
      },
      {
        Pno: "3",
        name: "GND",
        type: "GP",
        interface: "powerOUT",
        each_mandatory: false,
        con_port: "GND",
      },
      {
        Pno: "4",
        name: "PGND",
        type: "GP",
        interface: "powerOUT",
        each_mandatory: false,
        con_port: "PGND",
      },
      {
        Pno: "5",
        name: "SDA",
        type: "GP",
        interface: "powerGND",
        each_mandatory: false,
        con_port: "SDA",
      },
      {
        Pno: "6",
        name: "SCL",
        type: "GP",
        interface: "powerGND",
        each_mandatory: false,
        con_port: "SCL",
      },
      {
        Pno: "7",
        name: "INT",
        type: "GP",
        interface: "powerOUT",
        each_mandatory: false,
        con_port: "INT",
      },
    ],
  },
  // ... Add more options and JSON data
};

export default jsonOptions;
